#' Get the unique lineups from the possible lineup creator
#' 
#' @param all_possible_lineups All the lineups generated by \code{make_possible_lineups}
#' 
#' @export
make_unique_lineups <- function(all_possible_lineups) {
  
  lineup_matrix <- all_possible_lineups %>%
    dplyr::select(-dplyr::ends_with("_salary")) %>%
    as.matrix()
  
  ordered_lineups <- t(apply(lineup_matrix, 1, sort))
  
  lineupid_vec <- apply(ordered_lineups, 1, function(x) paste(x, collapse = "_"))
  
  unique_lineups <- all_possible_lineups %>%
    dplyr::mutate(lineup_id = lineupid_vec) %>%
    dplyr::group_by(lineup_id) %>%
    dplyr::filter(row_number() == 1) %>%
    dplyr::ungroup()
  
  return(unique_lineups)

}